on:
  push:
    branches:
      - hexo  # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # If your repository depends on submodule, please see: https://github.com/actions/checkout
      - name: Hexo Action
        # You may pin to the exact commit or the version.
        # uses: sma11black/hexo-action@08f5143fa402cdaccf9fc016d6bc91329f082eb0
        uses: sma11black/hexo-action@v1.0.4
        with:
          # The deploy key for Github Pages repo
          deploy_key: ${{secrets.GITHUB_TOKEN}}
          # Git commit messages to your GitHub Pages repository.
          commit_msg: "更新博客"
